name: flutter_application_practica
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  file_picker: ^10.2.0 
  geolocator: ^14.0.2
  url_launcher: ^6.2.1
  image_picker: ^1.0.7  # Versión más reciente
  image: ^4.0.17
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#1756A9" # Color de fondo (usa el azul principal de tu app)
  image: assets/splash.png # Ruta relativa correcta
  android: true
  ios: true
  web: true
